language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: "Tests"
      name: "Tests without proxy"
      script: npm run test
    - name: "Tests reports"
      script: npm run test-reports
    - name: "Tests rpki"
      script: npm run test-rpki
    - name: "Tests prefix generation"
      script: npm run test-generate
    - name: "Tests with proxy"
      before_script:
        - npm install -g anyproxy
        - nohup anyproxy --port 8001 &
        - ANYPROXY_PID=$!
      script:
        - npm run test-proxy
      after_script:
        - kill $ANYPROXY_PID


cache:
  npm: true
  directories:
    - node_modules

