environment: production

connectors:
  - file: connectorRIS
    name: ris
    params:
      carefulSubscription: true
      url: wss://ris-live.ripe.net/v1/ws/
      subscription:
        moreSpecific: true
        type: UPDATE
        host:
        socketOptions:
          includeRaw: false

monitors:
  - file: monitorHijack
    channel: hijack
    name: basic-hijack-detection

  - file: monitorNewPrefix
    channel: newprefix
    name: prefix-detection

  - file: monitorPath
    channel: path
    name: path-matching

  - file: monitorVisibility
    channel: visibility
    name: withdrawal-detection
    params:
      threshold: 10

reports:
  - file: reportFile
    channels:
      - hijack
      - newprefix
      - visibility
      - path

#  - file: reportEmail
#    channels:
#      - hijack
#      - newprefix
#      - visibility
#      - path
#    params:
#      senderEmail: bgpalerter@xxxx
#      # BGPalerter uses nodemailer.
#      # The smtp section can be configured with all the parameters available at https://nodemailer.com/smtp/
#      # the following are just the most useful one
#      smtp:
#        host: localhost42cbf5
#        port: 25
#        secure: false # If true the connection will use TLS when connecting to server. If false it will be still possible doing connection upgrade via STARTTLS
#        auth:
#          user: username
#          pass: password
#          type: login
#        tls:
#          rejectUnauthorized: true  # Reject unauthorized certificates
#      notifiedEmails:
#        default:
#          - joe@example.org
#          - noc@example.org
#
#  - file: reportSlack
#    channels:
#      - hijack
#      - newprefix
#      - visibility
#      - path
#    params:
#      colors:
#        hijack: '#d60b1c'
#        newprefix: '#fa9548'
#        visibility: '#fad648'
#        path: '#42cbf5'
#      hooks:
#        default: _YOUR_SLACK_WEBHOOK_URL_


checkStaleNotificationsSeconds: 60
notificationIntervalSeconds: 1800 # Repeat the same alert (which keeps being triggered) after x seconds
clearNotificationQueueAfterSeconds: 1900 # Stop with the alert for an event which didn't happen again in x seconds

# The file containing the monitored prefixes. Please see prefixes.yml for an example
# This is an array (use new lines and dashes!)
monitoredPrefixesFiles:
  - prefixes.yml

logging:
  directory: logs
  logRotatePattern: YYYY-MM-DD  # Whenever the pattern changes, a new file is created and the old one rotated
  zippedArchive: true
  maxSize: 20m
  maxFiles: 14d
  
checkForUpdatesAtBoot: true
